import React, { useState, useMemo } from 'react';
import { Search, Book, FileText, Box, AlertCircle, HelpCircle, ChevronRight, Download, Globe, Sparkles, Loader2, ArrowRight, Lightbulb, ChevronDown, ChevronUp } from 'lucide-react';
import { Language } from '../../types';
import { getResourceSearchResponse } from '../../services/geminiService';
import { FAQ_DATA } from '../../data/faqs';

interface ResourcesProps {
  lang: Language;
}

export const Resources: React.FC<ResourcesProps> = ({ lang }) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [aiData, setAiData] = useState<{ answer: string; relatedTopics: string[] } | null>(null);
  const [loading, setLoading] = useState(false);
  const [activeFaqTab, setActiveFaqTab] = useState<'general' | 'services' | 'corporate' | 'industries'>('general');
  const [openFaqIndex, setOpenFaqIndex] = useState<string | null>(null);

  const t = {
    heroTitle: lang === 'en' ? 'Wassel Smart' : 'واصل سمارت',
    heroSubtitle: lang === 'en' ? 'Instant answers powered by AI. Ask about shipping policies, customs, or packaging.' : 'إجابات فورية مدعومة بالذكاء الاصطناعي. اسأل عن سياسات الشحن، الجمارك، أو التغليف.',
    searchPlaceholder: lang === 'en' ? 'Ask a question (e.g., How to pack glass?)' : 'اطرح سؤالاً (مثال: كيفية تغليف الزجاج؟)',
    askBtn: lang === 'en' ? 'Ask AI' : 'اسأل AI',
    categoriesTitle: lang === 'en' ? 'Browse Topics' : 'تصفح المواضيع',
    faqTitle: lang === 'en' ? 'Common Questions' : 'أسئلة شائعة',
    downloadsTitle: lang === 'en' ? 'Forms & Downloads' : 'نماذج وتنزيلات',
    aiAnswer: lang === 'en' ? 'AI Answer:' : 'إجابة الذكاء الاصطناعي:',
    generatedBy: lang === 'en' ? 'Generated by Wassel AI' : 'تم الإنشاء بواسطة واصل AI',
    clear: lang === 'en' ? 'Clear Results' : 'مسح النتائج',
    viewGuide: lang === 'en' ? 'View Guide' : 'عرض الدليل',
    relatedTopics: lang === 'en' ? 'Related Topics:' : 'مواضيع ذات صلة:',
    tabs: {
        general: lang === 'en' ? 'General' : 'عام',
        services: lang === 'en' ? 'Services' : 'الخدمات',
        corporate: lang === 'en' ? 'Corporate' : 'الشركات',
        industries: lang === 'en' ? 'Sectors' : 'القطاعات',
    }
  };

  const categories = [
    {
      id: 'shipping-guides',
      title: lang === 'en' ? 'Shipping Guides' : 'أدلة الشحن',
      desc: lang === 'en' ? 'Step-by-step instructions for domestic and international shipping.' : 'تعليمات خطوة بخطوة للشحن المحلي والدولي.',
      icon: Book,
      color: 'bg-blue-100 text-blue-600'
    },
    {
      id: 'customs-regulations',
      title: lang === 'en' ? 'Customs Regulations' : 'اللوائح الجمركية',
      desc: lang === 'en' ? 'Understand import/export duties, taxes, and required documentation.' : 'فهم رسوم الاستيراد/التصدير، الضرائب، والمستندات المطلوبة.',
      icon: Globe,
      color: 'bg-green-100 text-green-600'
    },
    {
      id: 'packaging',
      title: lang === 'en' ? 'Packaging Advice' : 'نصائح التغليف',
      desc: lang === 'en' ? 'How to pack your items securely to prevent damage during transit.' : 'كيفية تغليف أغراضك بأمان لمنع التلف أثناء النقل.',
      icon: Box,
      color: 'bg-orange-100 text-orange-600'
    },
    {
      id: 'prohibited',
      title: lang === 'en' ? 'Prohibited Items' : 'المواد المحظورة',
      desc: lang === 'en' ? 'List of items that cannot be shipped locally or internationally.' : 'قائمة بالمواد التي لا يمكن شحنها محلياً أو دولياً.',
      icon: AlertCircle,
      color: 'bg-red-100 text-red-600'
    },
    {
      id: 'policies',
      title: lang === 'en' ? 'Terms & Policies' : 'الشروط والسياسات',
      desc: lang === 'en' ? 'Service terms, liability coverage, and privacy policies.' : 'شروط الخدمة، تغطية المسؤولية، وسياسات الخصوصية.',
      icon: FileText,
      color: 'bg-purple-100 text-purple-600'
    },
    {
      id: 'faqs',
      title: lang === 'en' ? 'General FAQs' : 'أسئلة عامة',
      desc: lang === 'en' ? 'Quick answers to common questions about tracking, accounts, and payments.' : 'إجابات سريعة على الأسئلة الشائعة حول التتبع، الحسابات، والدفع.',
      icon: HelpCircle,
      color: 'bg-teal-100 text-teal-600'
    }
  ];

  const downloads = [
    { name: lang === 'en' ? 'Commercial Invoice Template' : 'نموذج الفاتورة التجارية', size: '150 KB' },
    { name: lang === 'en' ? 'Customs Declaration Form' : 'نموذج التصريح الجمركي', size: '200 KB' },
    { name: lang === 'en' ? 'Claim Form' : 'نموذج المطالبة', size: '120 KB' },
  ];

  const handleSearch = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!searchQuery.trim()) return;
    
    setLoading(true);
    setAiData(null);

    try {
        const response = await getResourceSearchResponse(searchQuery);
        setAiData(response);
    } catch (err) {
        setAiData({
            answer: lang === 'en' ? "Sorry, I couldn't reach the knowledge base right now. Please try again." : "عذراً، لم أتمكن من الوصول إلى قاعدة المعرفة حالياً. يرجى المحاولة مرة أخرى.",
            relatedTopics: []
        });
    } finally {
        setLoading(false);
    }
  };

  const handleTopicClick = (topic: string) => {
      setSearchQuery(topic);
      setLoading(true);
      setAiData(null);
      getResourceSearchResponse(topic).then(response => {
          setAiData(response);
          setLoading(false);
      }).catch(() => setLoading(false));
  };

  const handleClear = () => {
      setSearchQuery('');
      setAiData(null);
  };

  // Helper to filter FAQs based on active tab
  const displayedFAQs = useMemo(() => {
      const allKeys = Object.keys(FAQ_DATA);
      let filteredKeys: string[] = [];

      if (activeFaqTab === 'general') {
          filteredKeys = ['general'];
      } else if (activeFaqTab === 'services') {
          filteredKeys = allKeys.filter(k => k.startsWith('service-') && !k.startsWith('service-corp-'));
      } else if (activeFaqTab === 'corporate') {
          filteredKeys = allKeys.filter(k => k.startsWith('service-corp-'));
      } else if (activeFaqTab === 'industries') {
          filteredKeys = allKeys.filter(k => !k.startsWith('service') && k !== 'general');
      }

      // Flatten the result
      let result: { category: string, q: string, a: string, id: string }[] = [];
      filteredKeys.forEach(key => {
          // Format category name for display
          let catName = key.replace('service-corp-', '').replace('service-', '').replace(/-/g, ' ');
          catName = catName.charAt(0).toUpperCase() + catName.slice(1);
          
          FAQ_DATA[key].forEach((item, idx) => {
              result.push({
                  category: key === 'general' ? '' : catName, // Only show category label if not general
                  q: lang === 'en' ? item.q.en : item.q.ar,
                  a: lang === 'en' ? item.a.en : item.a.ar,
                  id: `${key}-${idx}`
              });
          });
      });
      return result;
  }, [activeFaqTab, lang]);

  return (
    <div className="bg-gray-50 min-h-screen">
      {/* Hero Search Section - AI Themed */}
      {/* Increased padding-top to accommodate transparent fixed header */}
      <div className="bg-wassel-blue relative overflow-hidden pb-16 pt-36 md:pt-48">
        {/* Abstract Background Shapes */}
        <div className="absolute top-0 left-0 w-full h-full pointer-events-none">
            <div className="absolute top-[-10%] right-[-5%] w-96 h-96 bg-purple-500/20 rounded-full blur-3xl"></div>
            <div className="absolute bottom-[-10%] left-[-5%] w-96 h-96 bg-wassel-yellow/10 rounded-full blur-3xl"></div>
        </div>
        
        <div className="max-w-4xl mx-auto px-4 relative z-10 text-center">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 text-wassel-yellow text-xs font-bold uppercase tracking-wider mb-6 border border-white/20 animate-slide-up">
                <Sparkles className="w-4 h-4" /> {lang === 'en' ? 'AI Powered Knowledge' : 'معرفة مدعومة بالذكاء الاصطناعي'}
            </div>
            
            <h1 className="text-4xl md:text-5xl lg:text-6xl font-extrabold text-white mb-6 tracking-tight animate-slide-up delay-100">
                {t.heroTitle}
            </h1>
            <p className="text-lg md:text-xl text-blue-100 mb-10 max-w-2xl mx-auto animate-slide-up delay-200">
                {t.heroSubtitle}
            </p>

            {/* Smart Search Box */}
            <form onSubmit={handleSearch} className="relative max-w-2xl mx-auto animate-slide-up delay-300">
                <div className={`relative bg-white rounded-2xl shadow-2xl transition-all duration-300 ${loading ? 'scale-[0.98] opacity-90' : 'hover:scale-[1.01]'}`}>
                    <input 
                        type="text" 
                        value={searchQuery}
                        onChange={(e) => setSearchQuery(e.target.value)}
                        placeholder={t.searchPlaceholder}
                        className="w-full py-5 pl-14 rtl:pl-4 rtl:pr-14 pr-32 rtl:pl-32 rounded-2xl border-2 border-transparent focus:border-wassel-yellow focus:ring-0 text-lg text-gray-900 placeholder-gray-400 outline-none"
                    />
                    <Search className="absolute left-5 rtl:right-5 rtl:left-auto top-1/2 -translate-y-1/2 text-gray-400 w-6 h-6" />
                    
                    <div className="absolute right-2 rtl:left-2 rtl:right-auto top-2 bottom-2">
                        <button 
                            type="submit" 
                            disabled={loading || !searchQuery.trim()}
                            className="h-full bg-wassel-blue text-white px-6 rounded-xl font-bold hover:bg-wassel-darkBlue transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                        >
                            {loading ? <Loader2 className="animate-spin w-5 h-5" /> : <ArrowRight className="w-5 h-5 rtl:rotate-180" />}
                            <span className="hidden sm:inline">{t.askBtn}</span>
                        </button>
                    </div>
                </div>
            </form>
        </div>
      </div>

      {/* Content Container */}
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 -mt-8 relative z-20 pb-20">
        
        {/* AI Results Section */}
        {aiData && (
            <div className="max-w-4xl mx-auto mb-16 animate-pop">
                <div className="bg-white rounded-2xl shadow-xl border border-gray-100 p-6 md:p-8 relative overflow-hidden">
                    {/* Gradient Border Top */}
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-wassel-blue via-purple-500 to-wassel-yellow"></div>
                    
                    <div className="flex items-start gap-4">
                        <div className="p-3 bg-gradient-to-br from-indigo-500 to-purple-600 rounded-xl text-white shrink-0 shadow-lg">
                            <Sparkles className="w-6 h-6" />
                        </div>
                        <div className="flex-1 w-full">
                            <h3 className="text-lg font-bold text-gray-900 mb-3 flex items-center gap-2">
                                {t.aiAnswer}
                            </h3>
                            <div className="prose prose-blue max-w-none text-gray-700 leading-relaxed text-base md:text-lg">
                                {aiData.answer.split('\n').map((line, i) => (
                                    <p key={i} className="mb-2 last:mb-0">{line}</p>
                                ))}
                            </div>

                            {/* Related Topics */}
                            {aiData.relatedTopics && aiData.relatedTopics.length > 0 && (
                                <div className="mt-6 pt-6 border-t border-gray-100">
                                    <h4 className="text-sm font-bold text-gray-500 mb-3 flex items-center gap-2">
                                        <Lightbulb className="w-4 h-4 text-wassel-yellow" />
                                        {t.relatedTopics}
                                    </h4>
                                    <div className="flex flex-wrap gap-2">
                                        {aiData.relatedTopics.map((topic, idx) => (
                                            <button
                                                key={idx}
                                                onClick={() => handleTopicClick(topic)}
                                                className="px-3 py-1.5 bg-gray-100 text-gray-700 text-sm rounded-lg hover:bg-wassel-blue hover:text-white transition-colors border border-gray-200"
                                            >
                                                {topic}
                                            </button>
                                        ))}
                                    </div>
                                </div>
                            )}
                            
                            <div className="mt-4 pt-4 border-t border-gray-100 flex justify-between items-center">
                                <span className="text-xs text-gray-400 font-medium flex items-center gap-1">
                                    <Sparkles className="w-3 h-3" />
                                    {t.generatedBy}
                                </span>
                                <button onClick={handleClear} className="text-sm text-gray-500 hover:text-red-500 font-medium underline decoration-gray-300 hover:decoration-red-500 transition-all">
                                    {t.clear}
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        )}

        {/* Standard Resources Grid */}
        <div className="mb-16">
          <h2 className="text-2xl font-bold text-gray-900 mb-8 flex items-center gap-2">
              <Book className="w-6 h-6 text-wassel-blue" />
              {t.categoriesTitle}
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {categories.map((cat, i) => (
              <div 
                key={cat.id} 
                className="bg-white rounded-xl p-6 shadow-sm hover:shadow-md transition-all border border-gray-100 group cursor-pointer hover:-translate-y-1"
              >
                <div className={`${cat.color} w-12 h-12 rounded-lg flex items-center justify-center mb-4 group-hover:scale-110 transition-transform`}>
                  <cat.icon className="w-6 h-6" />
                </div>
                <h3 className="text-lg font-bold text-gray-900 mb-2 group-hover:text-wassel-blue transition-colors">
                  {cat.title}
                </h3>
                <p className="text-gray-500 text-sm mb-4 line-clamp-2">
                  {cat.desc}
                </p>
                <div className="flex items-center text-sm font-medium text-wassel-blue group-hover:underline">
                  {t.viewGuide}
                  <ChevronRight className="w-4 h-4 ml-1 rtl:mr-1 rtl:rotate-180" />
                </div>
              </div>
            ))}
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 md:gap-12">
          
          {/* FAQs Section */}
          <div className="lg:col-span-2">
            <h2 className="text-2xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                <HelpCircle className="w-6 h-6 text-wassel-blue" />
                {t.faqTitle}
            </h2>
            
            {/* Tabs */}
            <div className="flex gap-2 mb-6 overflow-x-auto pb-2 no-scrollbar">
                {(Object.keys(t.tabs) as Array<keyof typeof t.tabs>).map((key) => (
                    <button
                        key={key}
                        onClick={() => setActiveFaqTab(key)}
                        className={`px-4 py-2 rounded-full text-sm font-bold whitespace-nowrap transition-colors ${
                            activeFaqTab === key 
                            ? 'bg-wassel-blue text-white' 
                            : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
                        }`}
                    >
                        {t.tabs[key]}
                    </button>
                ))}
            </div>

            <div className="space-y-4">
              {displayedFAQs.map((faq) => {
                const isOpen = openFaqIndex === faq.id;
                return (
                    <div key={faq.id} className="bg-white rounded-lg shadow-sm border border-gray-100 overflow-hidden hover:shadow-md transition-shadow">
                        <button
                            onClick={() => setOpenFaqIndex(isOpen ? null : faq.id)}
                            className="w-full flex justify-between items-start text-left rtl:text-right p-6 hover:bg-gray-50 transition-colors"
                        >
                            <div className="flex items-start gap-3">
                                <div className="w-6 h-6 rounded-full bg-wassel-yellow/20 text-wassel-blue flex items-center justify-center shrink-0 text-sm font-bold mt-0.5">?</div>
                                <div>
                                    {faq.category && (
                                        <span className="block text-xs font-bold text-wassel-yellow uppercase tracking-wider mb-1">{faq.category}</span>
                                    )}
                                    <h3 className="text-lg font-medium text-gray-900">{faq.q}</h3>
                                </div>
                            </div>
                            {isOpen ? <ChevronUp className="w-5 h-5 text-gray-400 mt-1" /> : <ChevronDown className="w-5 h-5 text-gray-400 mt-1" />}
                        </button>
                        <div className={`transition-all duration-300 ease-in-out overflow-hidden ${isOpen ? 'max-h-48 opacity-100' : 'max-h-0 opacity-0'}`}>
                            <p className="text-gray-500 text-sm ml-14 rtl:mr-14 rtl:ml-6 pb-6 pr-6 rtl:pl-6 leading-relaxed border-t border-gray-100/50 pt-4">
                                {faq.a}
                            </p>
                        </div>
                    </div>
                );
              })}
              
              {displayedFAQs.length === 0 && (
                  <div className="text-center py-8 text-gray-500">
                      No FAQs found for this section.
                  </div>
              )}
            </div>
          </div>

          {/* Downloads Section */}
          <div className="lg:col-span-1">
            <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 sticky top-24">
              <h2 className="text-xl font-bold text-gray-900 mb-6 flex items-center gap-2">
                <Download className="w-5 h-5 text-wassel-blue" />
                {t.downloadsTitle}
              </h2>
              <div className="space-y-4">
                {downloads.map((file, i) => (
                  <div key={i} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg hover:bg-blue-50 transition-colors group cursor-pointer border border-transparent hover:border-blue-100">
                    <div className="flex items-center gap-3">
                      <FileText className="w-5 h-5 text-gray-400 group-hover:text-wassel-blue" />
                      <div>
                        <p className="text-sm font-medium text-gray-700 group-hover:text-gray-900">{file.name}</p>
                        <p className="text-xs text-gray-400">{file.size}</p>
                      </div>
                    </div>
                    <Download className="w-4 h-4 text-gray-400 group-hover:text-wassel-blue" />
                  </div>
                ))}
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};